services:
  # 1. Backend (Nest.js)
  backend:
    build: ./backend
    expose:
      - "3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://admin:Gay%4mE92%%7@postgres:5432/db
      REDIS_HOST: redis

  # 2. Frontend (Next.js)
  frontend:
    build: ./frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app         # Связываем папку на диске с папкой в контейнере
      - frontend_node_modules:/app/node_modules  # Используем именованный том, чтобы инициализировать модули из образа
    depends_on:
      - redis
    environment:
      - WATCHPACK_POLLING=true
      - REDIS_URL=redis://redis:6379

  # 3. Worker (Python)
  worker:
    build: ./worker
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  # 4. Database (PostgreSQL)
  db:
    image: postgres:17-alpine  # Используем легкую версию Alpine
    container_name: chess_postgres
    restart: always
    ports:
      - "5432:5432" # Пробрасываем порт наружу, чтобы ты мог подключиться через DBeaver
    environment:
      POSTGRES_USER: admin           # Твой логин
      POSTGRES_PASSWORD: Gay%4mE92%%7        # Твой пароль (для локальной разработки пойдет)
      POSTGRES_DB: chess_platform    # Имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data # !ВАЖНО: Чтобы данные не стирались при перезапуске

  # 5. Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning # Включаем сохранение данных на диск раз в минуту
    ports:
      - "6379:6379" # Проброс порта для локального подключения (RedisInsight)
    volumes:
      - redis_data:/data # Чтобы данные очереди не исчезли при перезагрузке

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules: