FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install drizzle-kit

COPY . .

EXPOSE 4983

CMD ["npx", "drizzle-kit", "studio", "--port", "4983", "--host", "0.0.0.0", "--config", "drizzle.config.ts"]